import express from "express";
import { authRouter } from "./auth.route";
import userRouter from "./user.route";
import paymentRouter from "./payment.route";
import vehicleRouter from "./vehicle.route";
import makeModelRouter from "./makeModel.route";
import bookingRouter from "./booking.route";
import searchRouter from "./search.router";
import reviewRouter from "./review.route";
import wishlistRouter from "./wishlist.route";
import documentRouter from "./document.route";
import notificationRouter from "./notification.route";
import tokenRouter from "./token.route";
import vendorVehicleRouter from "./vendor_vehicle.route";
import vendorDashboardRouter from "./vendor_dashboard.route";
import adminDashboardRoutes from './admin.dashboard.route';
import vehiclePreferenceRouter from './vehicle_preffer.route';
import vendorVehiclePrivacyPolicyRouter from './vendor_vehicle_privacy_policy.route';
import bankAccountRouter from './bank_account.route';
// import whatsappRouter from './whatsapp.route';
import otplessRouter from './otpless.route';
import imageUploadRouter from './image-upload.route';
import checkSocketConnectionRouter from './check-socket-connection';

export const router = express.Router();

router.use("/auth", authRouter);
router.use("/users", userRouter);
router.use("/payment", paymentRouter);
router.use("/vehicles", vehicleRouter);
router.use("/make-model", makeModelRouter);
router.use("/booking", bookingRouter);
router.use("/search", searchRouter);
router.use("/notification", notificationRouter);
router.use("/reviews", reviewRouter);
router.use("/wishlist", wishlistRouter);
router.use("/document", documentRouter);
router.use("/vendor-vehicle", vendorVehicleRouter);
router.use("/token", tokenRouter);
router.use("/vendor-dashboard", vendorDashboardRouter);
router.use('/admin/dashboard', adminDashboardRoutes);
router.use('/vehicle-preference', vehiclePreferenceRouter);
router.use('/vendor-vehicle-privacy-policy', vendorVehiclePrivacyPolicyRouter);
router.use('/payment', paymentRouter);
router.use('/bank', bankAccountRouter);
// router.use('/whatsapp', whatsappRouter);
router.use('/otpless', otplessRouter);
router.use('/image-upload', imageUploadRouter);
router.use('/check-socket-connection', checkSocketConnectionRouter);
